import ast
import operator
from config import COURSE_FEES


# ============================================================
# TOOL 1: GET COURSE FEE
# ============================================================

def get_course_fee(course_code: str) -> str:
    """
    Look up the fee for one course code.
    """

    course_code = course_code.strip().upper()

    fee = COURSE_FEES.get(course_code)

    if fee is not None:
        return str(fee)

    return f"Unknown course code: {course_code}"


# ============================================================
# TOOL 2: SAFE CALCULATOR
# ============================================================

# Allowed mathematical operators
_OPS = {
    ast.Add: operator.add,
    ast.Sub: operator.sub,
    ast.Mult: operator.mul,
    ast.Div: operator.truediv,
    ast.USub: operator.neg,
}


def _evaluate(node):
    """
    Safely evaluate a mathematical expression.
    """

    # Numbers
    if isinstance(node, ast.Constant) and isinstance(
        node.value, (int, float)
    ):
        return node.value

    # Binary operations:
    # +  -  *  /
    if isinstance(node, ast.BinOp) and type(node.op) in _OPS:
        left = _evaluate(node.left)
        right = _evaluate(node.right)

        return _OPS[type(node.op)](left, right)

    # Negative numbers
    if isinstance(node, ast.UnaryOp) and type(node.op) in _OPS:
        operand = _evaluate(node.operand)

        return _OPS[type(node.op)](operand)

    raise ValueError("Unsupported expression")


def calculator(expression: str) -> str:
    """
    Evaluate a basic arithmetic expression.

    Examples:
        100 + 200
        500 - 100
        20 * 5
        100 / 4
        (12000 + 18000) * 0.9
    """

    try:

        # Convert expression into an AST
        tree = ast.parse(expression, mode="eval")

        # Evaluate safely
        result = _evaluate(tree.body)

        return str(result)

    except Exception as error:

        return f"Calculator error: {error}"


# ============================================================
# TOOL FUNCTION MAP
# ============================================================

# This connects the tool name generated by the LLM
# to the actual Python function.

TOOL_FUNCTIONS = {
    "get_course_fee": get_course_fee,
    "calculator": calculator
}


# ============================================================
# TOOLS GIVEN TO THE LLM
# ============================================================

TOOLS = [

    # --------------------------------------------------------
    # GET COURSE FEE TOOL
    # --------------------------------------------------------

    {
        "type": "function",

        "function": {

            "name": "get_course_fee",

            "description": (
                "Get the fee in rupees for a single course code. "
                "Available course codes are CS101, AI202, and DS303."
            ),

            "parameters": {

                "type": "object",

                "properties": {

                    "course_code": {

                        "type": "string",

                        "description": (
                            "The course code. "
                            "Example: CS101, AI202, or DS303."
                        )
                    }
                },

                "required": [
                    "course_code"
                ]
            }
        }
    },


    # --------------------------------------------------------
    # CALCULATOR TOOL
    # --------------------------------------------------------

    {
        "type": "function",

        "function": {

            "name": "calculator",

            "description": (
                "Calculate a mathematical expression using "
                "numbers, +, -, *, / and parentheses."
            ),

            "parameters": {

                "type": "object",

                "properties": {

                    "expression": {

                        "type": "string",

                        "description": (
                            "A mathematical expression. "
                            "Example: (12000 + 18000) * 0.9"
                        )
                    }
                },

                "required": [
                    "expression"
                ]
            }
        }
    }
]


# ============================================================
# TEST THE TOOLS DIRECTLY
# ============================================================

if __name__ == "__main__":

    print("=" * 60)
    print("TESTING TOOLS")
    print("=" * 60)

    # Test course fee
    print()
    print("1. Course Fee Tool")

    print(
        "get_course_fee('AI202') ->",
        get_course_fee("AI202")
    )

    print(
        "get_course_fee('CS101') ->",
        get_course_fee("CS101")
    )

    print(
        "get_course_fee('DS303') ->",
        get_course_fee("DS303")
    )

    print(
        "get_course_fee('ABC999') ->",
        get_course_fee("ABC999")
    )


    # Test calculator
    print()
    print("2. Calculator Tool")

    print(
        "calculator('100 + 200') ->",
        calculator("100 + 200")
    )

    print(
        "calculator('500 - 100') ->",
        calculator("500 - 100")
    )

    print(
        "calculator('20 * 5') ->",
        calculator("20 * 5")
    )

    print(
        "calculator('100 / 4') ->",
        calculator("100 / 4")
    )

    print(
        "calculator('(12000 + 18000) * 0.9') ->",
        calculator("(12000 + 18000) * 0.9")
    )

    print(
        "calculator('15000 - 12000') ->",
        calculator("15000 - 12000")
    )


    print()
    print("=" * 60)
    print("TOOL TEST COMPLETED")
    print("=" * 60)